INSERT INTO party (party_id, display_name, max_party_size) VALUES
(1, 'Joe & Sarah Andaverde', 2),
(2, 'KC Anuforo & Guest', 2),
(3, 'Sean & Helen Aucoin', 2),
(4, 'Dan Baird & Guest', 2),
(5, 'Vicki Bales & Guest', 2),
(6, 'Jill & Richard Barbuto', 2),
(7, 'The Berry Family', 3),
(8, 'Derek & Courtney Blau', 2),
(9, 'Dan & Sharon Bock', 2),
(10, 'Brandon & Ashley Brinker', 2),
(11, 'Mary Beth & Dave Brown', 2),
(12, 'Jenny Brown & Guest', 2),
(13, 'Chris Brown & Guest', 2),
(14, 'Madelyn Buckner & Quincy Campbell Jr', 2),
(15, 'Brendan & Kelsey Carney', 2),
(16, 'Jeanne Cochrane & Guest', 2),
(17, 'Shannon & Melissa Colbern', 2),
(18, 'Ayre & Rebecca Cooney', 2),
(19, 'Madison Crocker & Guest', 2),
(20, 'Kalan Dahir & Guest', 2),
(21, 'The Dangler Family', 4),
(22, 'Chloe de la Peña & Lance Dick', 2),
(23, 'Frank & Tori Dietz', 2),
(24, 'Chris DiGiacinto', 1),
(25, 'Larry & Linda DiGiacinto', 2),
(26, 'Danny DiGiacinto', 1),
(27, 'Steve & Cathy DiGiacinto', 2),
(28, 'Mary Cathering DiGiacinto & Guest', 2),
(29, 'The DiGiacinto Family (Jon, Dani & Henry)', 3),
(30, 'Geoff DiGiacinto & Janelle Hensold', 2),
(31, 'The DiGiacinto Family (David, Martha & children)', 4),
(32, 'Sue DiGiacinto & Guest', 2),
(33, 'Jen DiGiacinto, Paula Formoso & Eli', 3),
(34, 'Roger & Mary Dykmann', 2),
(35, 'The Feist Family', 4),
(36, 'Chris Gabel & Guest', 2),
(37, 'Mary Catherine Gerling & Guest', 2),
(38, 'Brian & Mary Gerling', 2),
(39, 'Emily Gerling & Guest', 2),
(40, 'The Gile Family', 4),
(41, 'Mike & Maureen Huffer', 2),
(42, 'Nate & Emily Kalberer', 2),
(43, 'Brooke Katterhenry & Guest', 2),
(44, 'Dustin & Christine Kessler', 2),
(45, 'Matt & Lizzie Kieffer', 2),
(46, 'Kelly & Kathy Kirby', 2),
(47, 'Dan & Jennifer Kroymann', 2),
(48, 'Dan & Natalie LaBoube', 2),
(49, 'Jim & Joyce Lawson', 2),
(50, 'Gene & Georgann Lee', 2),
(51, 'Kyle Lefler & Guest', 2),
(52, 'Paul & Penny Leibbrand', 2),
(53, 'Bob & Deborah Luby', 2),
(54, 'The Kilgore Family', 4),
(55, 'The Luby Family (Tim, Pam & children)', 5),
(56, 'The Luby Family (Joe, Andrea & children)', 5),
(57, 'Steve Luby & Guests', 2),
(58, 'Ryan Luby & Guest', 2),
(59, 'Michelle Luby & Guest', 2),
(60, 'Ray Luby & Guest', 2),
(61, 'Ken & Maureen Teagle', 2),
(62, 'The Waddell Family', 5),
(63, 'Patricia Luby', 1),
(64, 'Conner Magin & Cameron White', 2),
(65, 'Shelbie Martel & Tyler Wedel', 2),
(66, 'Bill & Donna Martel', 2),
(67, 'Joe McGuff & Guest', 2),
(68, 'Ryan & Kate McNair', 2),
(69, 'Meghan McNally & Guest', 2),
(70, 'Lauren & Will Miller', 2),
(71, 'Marj Moran & Guest', 2),
(72, 'Kathy Morton & Guest', 2),
(73, 'Tim & Carol Munda', 2),
(74, 'Jim & Emilie Munda', 2),
(75, 'Nate Munda & Guest', 2),
(76, 'The Munda Family (Brian, Guest & children)', 6),
(77, 'Josh Munda & Guests', 4),
(78, 'Chris & Frank Munda', 2),
(79, 'Dan & Mary Kay Munda', 2),
(80, 'Roland & Shirlee Munda', 2),
(81, 'Elyssa Munda & Paul Rhodes', 2),
(82, 'Justin Noggle & Guest', 2),
(83, 'Bill & Margie Ortgeisen', 2),
(84, 'Mike & Jennifer Owens', 2),
(85, 'Mark & Colette Popp', 2),
(86, 'Brandon Powers & Guest', 2),
(87, 'Elizabeth Pratt', 1),
(88, 'Logan Pyle & Guest', 2),
(89, 'Anita Ranhotra & Guest', 2),
(90, 'Stephen Reddekopp & Guest', 2),
(91, 'The Rieter Family', 4),
(92, 'Charlie & Sara Rock', 2),
(93, 'Peter & Barb Roszel', 2),
(94, 'The Rush Family', 6),
(95, 'Jake & Gina Rush', 2),
(96, 'Mike & Vicki Ryan', 2),
(97, 'Matt & Courtney Sklenar', 2),
(98, 'Scott & Christie Smerchek', 2),
(99, 'Aaron & Angie Smith', 2),
(100, 'Father Richard Storey', 1),
(101, 'Andrew Tenbrink & Guest', 2),
(102, 'Alex Walton & Guest', 2),
(103, 'Jackie Washutt & Guest', 2),
(104, 'Ron & Carlie Wike', 2),
(105, 'Cathy Wood & Guest', 2),
(106, 'The Zuchowski Family', 2);
