INSERT INTO party (party_id, display_name, max_party_size) VALUES
(1, 'The Andaverde Family', 3),
(2, 'KC Anuforo & Guest', 2),
(3, 'Sean & Helen Aucoin', 2),
(4, 'Dan Baird & Guest', 2),
(5, 'Vicki Bales & Guest', 2),
(6, 'Jill & Richard Barbuto', 4),
(7, 'The Berry Family', 3),
(8, 'Derek & Courtney Blau', 2),
(9, 'Dan & Sharon Bock', 2),
(10, 'Brandon & Ashley Brinker', 3),
(11, 'Mary Beth & Dave Brown', 2),
(12, 'Jenny Brown & Guest', 2),
(13, 'Chris Brown & Guest', 2),
(14, 'Madelyn Buckner & Quincy Campbell Jr', 2),
(15, 'Brendan & Kelsey Carney', 2),
(16, 'Jeanne Cochrane & Guest', 2),
(17, 'Shannon & Melissa Colbern', 2),
(18, 'Ayre & Rebecca Cooney', 2),
(19, 'Madison Crocker & Guest', 2),
(20, 'Kalan Dahir & Guest', 2),
(21, 'The Dangler Family', 4),
(22, 'Chloe De La Peña & Lance Dick', 2),
(23, 'Frank & Tori Dietz', 2),
(24, 'Chris DiGiacinto', 1),
(25, 'Larry & Linda DiGiacinto', 2),
(26, 'Danny DiGiacinto', 1),
(27, 'Steve & Cathy DiGiacinto', 2),
(28, 'Mary Catherine DiGiacinto & Guest', 2),
(29, 'Jon, Dani & Henry DiGiacinto', 3),
(30, 'Geoff DiGiacinto & Guest', 2),
(31, 'The DiGiacinto Family (David, Martha & children)', 4),
(32, 'Sue DiGiacinto & Guest', 2),
(33, 'Jen, Paula, & Eli', 3),
(34, 'Roger & Mary Dykmann', 2),
(35, 'The Feist Family', 4),
(36, 'Chris Gabel & Guest', 2),
(37, 'Mary Catherine Gerling & Guest', 2),
(38, 'Brian & Mary Gerling', 2),
(39, 'Emily Gerling & Guest', 2),
(40, 'The Gile Family', 4),
(41, 'Mike & Maureen Huffer', 2),
(42, 'Nate & Emily Kalberer', 2),
(43, 'Brooke Katterhenry & Guest', 2),
(44, 'Dustin & Christine Kessler', 2),
(45, 'Matt & Lizzie Kieffer', 2),
(46, 'Kelly & Kathy Kirby', 2),
(47, 'Dan & Jennifer Kroymann', 2),
(48, 'Dan & Natalie LaBoube', 2),
(49, 'Jim & Joyce Lawson', 2),
(50, 'Gene & Georgann Lee', 2),
(51, 'Kyle Lefler & Guest', 2),
(52, 'Paul & Penny Leibbrand', 2),
(53, 'Bob & Deborah Luby', 2),
(54, 'Mary Anne & Chuck Kilgore', 2),
(55, 'Tim, Pam, Craig, and Megan Luby', 4),
(56, 'The Luby Family (Joe, Andrea & children)', 5),
(57, 'Steve Luby & Guest', 2),
(58, 'Ryan Luby & Guest', 2),
(59, 'Michelle Luby & Guest', 2),
(60, 'Ray Luby & Guest', 2),
(61, 'Ken & Maureen Teagle', 2),
(62, 'The Waddell Family', 5),
(63, 'Patricia Luby', 1),
(64, 'Conner Magin & Cameron White', 2),
(65, 'Shelbie Martel & Tyler Wedel', 2),
(66, 'Bill & Donna Martel', 2),
(67, 'Joe McGuff & Guest', 2),
(68, 'Ryan & Kate McNair', 2),
(69, 'Meghan McNally & Guest', 2),
(70, 'Lauren & Will Miller', 2),
(71, 'Marj Moran & Guest', 2),
(72, 'Kathy Morton & Guest', 2),
(73, 'Tim & Carol Munda', 2),
(74, 'Jim & Emilie Munda', 2),
(75, 'Nate Munda', 1),
(76, 'The Munda Family (Brian, Guest & children)', 6),
(77, 'Josh Munda & Guests', 4),
(78, 'Chris & Frank Munda', 2),
(79, 'Dan & Mary Kay Munda', 2),
(80, 'Roland & Shirlee Munda', 2),
(81, 'Elyssa Munda & Paul Rhodes', 2),
(82, 'Justin Noggle & Tara Davis', 2),
(83, 'Bill & Margie Ortgeisen', 2),
(84, 'Mike & Jennifer Owens', 2),
(85, 'Mark & Colette Popp', 2),
(86, 'Brandon Powers & Guest', 2),
(87, 'Elizabeth Pratt', 1),
(88, 'Logan Pyle & Guest', 2),
(89, 'Anita Ranhotra & Guest', 2),
(90, 'Stephen Reddekopp & Emily Ousley', 2),
(91, 'The Rieter Family', 4),
(92, 'Charlie & Sara Rock', 2),
(93, 'Peter & Barb Roszel', 2),
(94, 'The Rush Family', 6),
(95, 'Jake & Gina Rush', 2),
(96, 'Mike & Vicki Ryan', 2),
(97, 'Matt & Courtney Hosea', 2),
(98, 'Scott & Christie Smerchek', 3),
(99, 'Aaron & Angie Smith', 2),
(100, 'Father Richard Storey', 1),
(101, 'Andrew Tenbrink & Guest', 2),
(102, 'Alex Walton & Guest', 2),
(103, 'Jackie Washutt & Guest', 2),
(104, 'Ron & Carlie Wike', 2),
(105, 'Cathy Wood & Guest', 2),
(106, 'Bob & Linda Zuchowski', 2),
(107, 'Jordan Marquess & Guest', 2),
(108, 'Tim & Stephanie Alley', 2),
(109, 'Marty & Brenda Clifford', 2),
(110, 'Charlie Kilgore & Guest', 2),
(111, 'Janie Kilgore & Guest', 2),
(112, 'Scott Luby & Guest', 2),
(113, 'Matt & Laura Murphy', 2),
(114, 'Jaison Smulski & Michelle Freeman', 2),
(115, 'Robert & Denis Smulski', 2),
(116, 'Mark & Jane Sullivan', 2),
(117, 'Robin & Don Sumple', 2),
(118, 'Frank & Nina Willis', 2),
(119, 'Zach & Erin Wolling', 2),
(120, 'Bret & Michelle Toelkes', 2),
(121, 'Dale & Catherine Romme', 2),
(122, 'Michael & Kimberly Taylor', 2),
(123, 'Angie & Steve Freund', 2),
(124, 'Jay & Jannie Morrison', 2),
(125, 'Bill & Connie Johnson', 2),
(126, 'Ed & Ann VanLeeuwen', 2),
(127, 'Dick & Sandy Heydinger', 2),
(128, 'Charlene & Roy Green', 2),
(129, 'Elaine & Bill Mayor', 2),
(130, 'Bobbie & Rob Kuehl', 2);

INSERT INTO guest (party_id, first_name, last_name) VALUES
(1, 'Joe', 'Andaverde'),
(1, 'Sarah', 'Andaverde'),
(2, 'KC', 'Anuforo'),
(3, 'Helen', 'Aucoin'),
(3, 'Sean', 'Aucoin'),
(4, 'Dan', 'Baird'),
(5, 'Vicki', 'Bales'),
(6, 'Jill', 'Barbuto'),
(6, 'Richard', 'Barbuto'),
(7, 'Sol', 'Berry'),
(7, 'Becky', 'Berry'),
(8, 'Derek', 'Blau'),
(8, 'Courtney', 'Blau'),
(9, 'Dan', 'Bock'),
(9, 'Sharon', 'Bock'),
(10, 'Brandon', 'Brinker'),
(10, 'Ashley', 'Brinker'),
(11, 'Mary Beth', 'Brown'),
(11, 'Dave', 'Brown'),
(12, 'Jenny', 'Brown'),
(13, 'Chris', 'Brown'),
(14, 'Madelyn', 'Buckner'),
(14, 'Quincy', 'Campbell'),
(15, 'Brendan', 'Carney'),
(15, 'Kelsey', 'Carney'),
(16, 'Jeanne', 'Cochrane'),
(17, 'Shannon', 'Colbern'),
(17, 'Melissa', 'Colbern'),
(18, 'Ayre', 'Cooney'),
(18, 'Rebecca', 'Cooney'),
(19, 'Madison', 'Crocker'),
(20, 'Kalan', 'Dahir'),
(21, 'Angie', 'Dangler'),
(21, 'Brett', 'Dangler'),
(22, 'Chloe', 'De La Peña'),
(22, 'Lance', 'Dick'),
(23, 'Tori', 'Dietz'),
(23, 'Frank', 'Dietz'),
(24, 'Chris', 'DiGiacinto'),
(25, 'Larry', 'DiGiacinto'),
(25, 'Linda', 'DiGiacinto'),
(26, 'Danny', 'DiGiacinto'),
(27, 'Steve', 'DiGiacinto'),
(27, 'Cathy', 'DiGiacinto'),
(28, 'Mary Catherine', 'DiGiacinto'),
(29, 'Jon', 'DiGiacinto'),
(29, 'Dani', 'DiGiacinto'),
(30, 'Geoff', 'DiGiacinto'),
(31, 'David', 'DiGiacinto'),
(31, 'Martha', 'DiGiacinto'),
(32, 'Sue', 'DiGiacinto'),
(33, 'Jen', 'DiGiacinto'),
(33, 'Paula', 'Formoso'),
(34, 'Roger', 'Dykmann'),
(34, 'Mary', 'Dykmann'),
(35, 'Derek', 'Feist'),
(35, 'Kim', 'Feist'),
(36, 'Chris', 'Gabel'),
(37, 'Mary Catherine', 'Gerling'),
(38, 'Brian', 'Gerling'),
(38, 'Mary', 'Gerling'),
(39, 'Emily', 'Gerling'),
(40, 'Jen', 'Gile'),
(40, 'Luke', 'Gile'),
(41, 'Mike', 'Huffer'),
(41, 'Maureen', 'Huffer'),
(42, 'Nate', 'Kalberer'),
(42, 'Emily', 'Kalberer'),
(43, 'Brooke', 'Katterhenry'),
(44, 'Dustin', 'Kessler'),
(44, 'Christine', 'Kessler'),
(45, 'Matt', 'Kieffer'),
(45, 'Lizzie', 'Kieffer'),
(46, 'Kelly', 'Kirby'),
(46, 'Kathy', 'Kirby'),
(47, 'Dan', 'Kroymann'),
(47, 'Jennifer', 'Kroymann'),
(48, 'Dan', 'LaBoube'),
(48, 'Natalie', 'LaBoube'),
(49, 'Jim', 'Lawson'),
(49, 'Joyce', 'Lawson'),
(50, 'Gene', 'Lee'),
(50, 'Georgann', 'Lee'),
(51, 'Kyle', 'Lefler'),
(52, 'Paul', 'Leibbrand'),
(52, 'Penny', 'Leibbrand'),
(53, 'Bob', 'Luby'),
(53, 'Deborah', 'Luby'),
(54, 'Mary Anne', 'Kilgore'),
(54, 'Chuck', 'Kilgore'),
(55, 'Tim', 'Luby'),
(55, 'Pam', 'Luby'),
(56, 'Joe', 'Luby'),
(56, 'Andrea', 'Luby'),
(57, 'Steve', 'Luby'),
(57, 'Jeni', 'Luby'),
(58, 'Ryan', 'Luby'),
(59, 'Michelle', 'Luby'),
(60, 'Ray', 'Luby'),
(61, 'Ken', 'Teagle'),
(61, 'Maureen', 'Teagle'),
(62, 'Jean', 'Waddell'),
(62, 'Jim', 'Waddell'),
(63, 'Patricia', 'Luby'),
(64, 'Conner', 'Magin'),
(64, 'Cameron', 'White'),
(65, 'Shelbie', 'Martel'),
(65, 'Tyler', 'Wedel'),
(66, 'Bill', 'Martel'),
(66, 'Donna', 'Martel'),
(67, 'Joe', 'McGuff'),
(68, 'Ryan', 'McNair'),
(68, 'Kate', 'McNair'),
(69, 'Meghan', 'McNally'),
(70, 'Lauren', 'Miller'),
(70, 'Will', 'Miller'),
(71, 'Marj', 'Moran'),
(72, 'Kathy', 'Morton'),
(73, 'Tim', 'Munda'),
(73, 'Carol', 'Munda'),
(74, 'Jim', 'Munda'),
(74, 'Emilie', 'Munda'),
(75, 'Nate', 'Munda'),
(76, 'Brian', 'Munda'),
(77, 'Josh', 'Munda'),
(78, 'Chris', 'Munda'),
(78, 'Frank', 'Munda'),
(79, 'Dan', 'Munda'),
(79, 'Mary Kay', 'Munda'),
(80, 'Roland', 'Munda'),
(80, 'Shirlee', 'Munda'),
(81, 'Elyssa', 'Munda'),
(81, 'Paul', 'Rhodes'),
(82, 'Justin', 'Noggle'),
(82, 'Tara', 'Davis'),
(83, 'Bill', 'Ortgeisen'),
(83, 'Margie', 'Ortgeisen'),
(84, 'Mike', 'Owens'),
(84, 'Jennifer', 'Owens'),
(85, 'Mark', 'Popp'),
(85, 'Colette', 'Popp'),
(86, 'Brandon', 'Powers'),
(87, 'Elizabeth', 'Pratt'),
(88, 'Logan', 'Pyle'),
(89, 'Anita', 'Ranhotra'),
(90, 'Stephen', 'Reddekopp'),
(91, 'Suzanne', 'Rieter'),
(91, 'Robert', 'Rieter'),
(92, 'Charlie', 'Rock'),
(92, 'Sara', 'Rock'),
(93, 'Peter', 'Roszel'),
(93, 'Barb', 'Roszel'),
(94, 'Danny', 'Rush'),
(94, 'Jerre', 'Rush'),
(94, 'Luke', 'Rush'),
(94, 'Erica', 'Halter'),
(95, 'Jake', 'Rush'),
(95, 'Gina', 'Rush'),
(96, 'Mike', 'Ryan'),
(96, 'Vicki', 'Ryan'),
(97, 'Matt', 'Hosea'),
(97, 'Courtney', 'Hosea'),
(98, 'Scott', 'Smerchek'),
(98, 'Christie', 'Smerchek'),
(99, 'Aaron', 'Smith'),
(99, 'Angie', 'Smith'),
(100, 'Richard', 'Storey'),
(101, 'Andrew', 'Tenbrink'),
(102, 'Alex', 'Walton'),
(103, 'Jackie', 'Washutt'),
(104, 'Ron', 'Wike'),
(104, 'Carlie', 'Wike'),
(105, 'Cathy', 'Wood'),
(106, 'Bob', 'Zuchowski'),
(106, 'Linda', 'Zuchowski'),
(107, 'Jordan', 'Marquess'),
(108, 'Stephanie', 'Alley'),
(108, 'Tim', 'Alley'),
(109, 'Marty', 'Clifford'),
(109, 'Brenda', 'Clifford'),
(110, 'Charlie', 'Kilgore'),
(111, 'Janie', 'Kilgore'),
(112, 'Scott', 'Luby'),
(113, 'Laura', 'Murphy'),
(113, 'Matt', 'Murphy'),
(114, 'Jaison', 'Smulski'),
(114, 'Michelle', 'Freeman'),
(115, 'Robert', 'Smulski'),
(115, 'Denise', 'Smulski'),
(116, 'Jane', 'Sullivan'),
(116, 'Mark', 'Sullivan'),
(117, 'Robin', 'Sumple'),
(117, 'Don', 'Sumple'),
(118, 'Frank', 'Willis'),
(118, 'Nina', 'Willis'),
(119, 'Erin', 'Wolling'),
(119, 'Zach', 'Wolling'),
(120, 'Michelle', 'Toelkes'),
(120, 'Bret', 'Toelkes'),
(121, 'Dale', 'Romme'),
(121, 'Catherine', 'Romme'),
(122, 'Michael', 'Taylor'),
(122, 'Kimberly', 'Taylor'),
(123, 'Angie', 'Freund'),
(123, 'Steve', 'Freund'),
(124, 'Jay', 'Morrison'),
(124, 'Jannie', 'Morrison'),
(125, 'Bill', 'Johnson'),
(125, 'Connie', 'Johnson'),
(126, 'Ed', 'VanLeeuwen'),
(126, 'Ann', 'VanLeeuwen'),
(127, 'Dick', 'Heydinger'),
(127, 'Sandy', 'Heydinger'),
(128, 'Charlene', 'Green'),
(128, 'Roy', 'Green'),
(129, 'Elaine', 'Mayor'),
(129, 'Bill', 'Mayor'),
(130, 'Bobbie', 'Kuehl'),
(130, 'Rob', 'Kuehl');
