INSERT INTO party (party_id, display_name, max_party_size) VALUES
(1, 'Joe & Sarah &averde', 2),
(2, 'KC Anuforo & Guest', 2),
(3, 'Sean & Helen Aucoin', 2),
(4, 'Dan Baird & Guest', 2),
(5, 'Vicki Bales & Guest', 2),
(6, 'Jill & Richard Barbuto', 2),
(7, 'The Berry Family', 3),
(8, 'Derek & Courtney Blau', 2),
(9, 'Dan & Sharon Bock', 2),
(10, 'Br&on & Ashley Brinker', 2),
(11, 'Mary Beth & Dave Brown', 2),
(12, 'Jenny Brown & Guest', 2),
(13, 'Chris Brown & Guest', 2),
(14, 'Madelyn Buckner & Quincy Campbell Jr', 2),
(15, 'Brendan & Kelsey Carney', 2),
(16, 'Jeanne Cochrane & Guest', 2),
(17, 'Shannon & Melissa Colbern', 2),
(18, 'Ayre & Rebecca Cooney', 2),
(19, 'Madison Crocker & Guest', 2),
(20, 'Kalan Dahir & Guest', 2),
(21, 'The Dangler Family', 4),
(22, 'Kalan Dahir & Guest', 2),
(23, 'Chloe de la Peña & Lance Dick', 2),
(24, 'Frank & Tori Dietz', 2),
(25, 'Chris DiGiacinto', 1),
(26, 'Larry & Linda DiGiacinto', 2),
(27, 'Danny DiGiacinto', 1),
(28, 'Steve & Cathy DiGiacinto', 2),
(29, 'Mary Cathering DiGiacinto & Guest', 2),
(30, 'The DiGiacinto Family (Jon, Dani & Henry)', 3),
(31, 'Geoff DiGiacinto & Janelle Hensold', 2),
(32, 'The DiGiacinto Family (David, Martha & children)', 4),
(33, 'Sue DiGiacinto & Guest', 2),
(34, 'Jen DiGiacinto, Paula Formoso & Eli', 3),
(35, 'Roger & Mary Dykmann', 2),
(36, 'The Feist Family', 4),
(37, 'Chris Gabel & Guest', 2),
(38, 'Mary Catherine Gerling & Guest', 2),
(39, 'Brian & Mary Gerling', 2),
(40, 'Emily Gerling & Guest', 2),
(41, 'The Gile Family', 4),
(42, 'Mike & Maureen Huffer', 2),
(43, 'Nate & Emily Kalberer', 2),
(44, 'Brooke Katterhenry & Guest', 2),
(45, 'Dustin & Christine Kessler', 2),
(46, 'Matt & Lizzie Kieffer', 2),
(47, 'Kelly & Kathy Kirby', 2),
(48, 'Dan & Jennifer Kroymann', 2),
(49, 'Dan & Natalie LaBoube', 2),
(50, 'Jim & Joyce Lawson', 2),
(51, 'Gene & Georgann Lee', 2),
(52, 'Kyle Lefler & Guest', 2),
(53, 'Paul & Penny Leibbr&', 2),
(54, 'Bob & Deborah Luby', 2),
(55, 'The Kilgore Family', 4),
(56, 'The Luby Family (Tim, Pam & children)', 5),
(57, 'The Luby Family (Joe, Andrea & children)', 5),
(58, 'Steve Luby & Guests', 3),
(59, 'Ryan Luby & Guest', 2),
(60, 'Michelle Luby & Guest', 2),
(61, 'Ray Luby & Guest', 2),
(62, 'Ken & Maureen Teagle', 2),
(63, 'The Waddell Family', 5),
(64, 'Patricia Luby', 1),
(65, 'Conner Magin & Cameron White', 2),
(66, 'Shelbie Martel & Tyler Wedel', 2),
(67, 'Bill & Donna Martel', 2),
(68, 'Joe McGuff & Guest', 2),
(69, 'Ryan & Kate McNair', 2),
(70, 'Meghan McNally & Guest', 2),
(71, 'Lauren & Will Miller', 2),
(72, 'Marj Moran & Guest', 2),
(73, 'Kathy Morton & Guest', 2),
(74, 'Tim & Carol Munda', 2),
(75, 'Jim & Emilie Munda', 2),
(76, 'Nate Munda & Guest', 2),
(77, 'Nate Munda & Guest', 2),
(78, 'The Munda Family (Brian, Guest & children)', 6),
(79, 'Josh Munda & Guests', 4),
(80, 'Chris & Frank Munda', 2),
(81, 'Dan & Mary Kay Munda', 2),
(82, 'Roland & Shirlee Munda', 2),
(83, 'Elyssa Munda & Paul Rhodes', 2),
(84, 'Justin Noggle & Guest', 2),
(85, 'Bill & Margie Ortgeisen', 2),
(86, 'Mike & Jennifer Owens', 2),
(87, 'Mark & Colette Popp', 2),
(88, 'Brandon Powers & Guest', 2),
(89, 'Elizabeth Pratt', 1),
(90, 'Logan Pyle & Guest', 2),
(91, 'Anita Ranhotra & Guest', 2),
(92, 'Stephen Reddekopp & Guest', 2),
